version: '3'

# Run as
# docker-compose build; docker-compose up -d
# Check with
# docker ps
# Then check the logs with
# docker logs --tail 50 $container_id
# docker-compose images
# docker-compose logs --tail 20 repo_name


services:

  redis:
    image: redis
    ports:
      - 6379
    networks:
      - app-tier

  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - app-tier
    #command: sh -c "celery -A celery_tasks worker --loglevel=info -f celery.logs"
    #command: tail -f /dev/null

networks:
  app-tier:
    driver: bridge

#CLEANUP
#docker-compose down
#docker rmi carvana-exercise_frontend
#docker rmi carvana-exercise_backend
