version: '3'

services:

  redis:
    image: redis
    ports:
      - 6379
    networks:
      - app-tier

  python_app:
    container_name: python_app_container
    build:
      context: .
      dockerfile: Dockerfile
    image: python_app_image
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
